# Generated by Django 2.2.7 on 2019-12-07 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpath', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='toUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='messages',
            table='messages_db1',
        ),
    ]
