# Generated by Django 2.2.6 on 2019-10-07 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('descpath', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='toUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='messages',
            table='messages_db',
        ),
        migrations.DeleteModel(
            name='Coreuser',
        ),
    ]
