# Generated by Django 2.2.6 on 2019-10-11 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('descpath', '0002_auto_20191007_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='question_text',
        ),
        migrations.AlterModelTable(
            name='messages',
            table=None,
        ),
    ]
