# Generated by Django 2.2.7 on 2019-11-17 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('descpath', '0003_auto_20191011_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='toUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='desctouser', to=settings.AUTH_USER_MODEL),
        ),
    ]
